# database connection string to Redshift to export the statistics
database: dbname=scoville

providers:
  # configuration of where to find the provider (at the time of writing, only
  # mapzen is supported) tiles.
  mapzen:
    type: mapzen
    host: vector.dev.mapzen.com
    api_key: YOUR_API_KEY_HERE

# interval in seconds between grabbing a tile
run_interval: 60

# logging configuration - see logging.example.conf for an example
logging_config: logging.conf

# URL or file name of a list of tiles with counts to use to create a realistic
# stream of tile coordinates. the file should be zoom, x, y, count separated by
# pipe characters "|".
tiles: tiles.txt

# string description of the region to use when annotating statistics.
region: us-east-1
